[ci skip] Pushing deployment files for namespace and service accounts
Signed-off-by: kaverikhaneja <kaveri.khaneja@accenture.com>

diff --git a/platforms/hyperledger-besu/charts/create_crypto_ibft/templates/job.yaml b/platforms/hyperledger-besu/charts/create_crypto_ibft/templates/job.yaml
--- a/platforms/hyperledger-besu/charts/create_crypto_ibft/templates/job.yaml
+++ b/platforms/hyperledger-besu/charts/create_crypto_ibft/templates/job.yaml
@@ -53,17 +53,15 @@ spec:
               value: "/cryptocheck"
             - name: ITEM_NAME
               value: {{ .Values.metadata.item.name}}
-          command: ["sh", "-c"]
+          command: ["/bin/bash", "-c"]
           args:
           - |-
-             #!/usr/bin/env sh
-             
               validateVaultResponse () {
                 if echo ${2} | grep "errors"; then
                   echo "ERROR: unable to retrieve ${1}: ${2}"
                   exit 1
                 fi
-                if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
+                if  [ "$3" == "LOOKUPSECRETRESPONSE" ];
                 then
                   http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
                   --header "X-Vault-Token: ${VAULT_TOKEN}" \
@@ -101,7 +99,7 @@ spec:
               fi
               echo "Done checking for secrets in vault"
         containers:
-        - name: crypto-ibft
+        - name: create-crypto-ibft
           image: {{ .Values.image.repository }}
           imagePullPolicy: {{ .Values.image.pullPolicy }}
           volumeMounts:
@@ -117,7 +115,7 @@ spec:
             - name: NODE_TYPE
               value: {{ .Values.node.type }}
             - name: ADD_NEW_ORG
-              value: {{ .Values.checks.add_new_org | quote }}
+              value: {{ .Values.checks.add_new_org }}
             - name: COMPONENT_NAME
               value: {{ .Values.metadata.name }}
             - name: VAULT_SECRET_PREFIX
@@ -133,23 +131,43 @@ spec:
           command: ["/bin/bash", "-c"]
           args:
           - |-
-            # curl --version
+            #installing jq
             curl -L -o /opt/besu/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
             chmod +x /opt/besu/bin/jq
-            # jq --version
+            jq --version
+
+            validateVaultResponse () {
+                if echo ${2} | grep "errors"; then
+                  echo "ERROR: unable to retrieve ${1}: ${2}"
+                  exit 1
+                fi
+                if  [ "$3" == "LOOKUPSECRETRESPONSE" ];
+                then
+                  http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
+                  --header "X-Vault-Token: ${VAULT_TOKEN}" \
+                  ${VAULT_ADDR}/v1/${1})
+                  curl_response=$?
+                  if test "$http_code" != "200" ; then
+                    echo "Http response code from Vault - $http_code and curl_response - $curl_response"
+                    if test "$curl_response" != "0"; then
+                      echo "Error: curl command failed with error code - $curl_response"
+                      exit 1
+                    fi
+                  fi
+                fi
+              }
             
             if [ -e /cryptocheck/present.txt ]
             then
               echo "Crypto Material already present in the vault."
-              # exit 0
+              exit 0
             fi
-
+            
+            #Create build folder to store crypto material
             BUILD_PATH="build"
-            
             mkdir -p ${BUILD_PATH}
-            #mkdir -p ${BUILD_PATH}/crypto
-            
-            #Get information about each node present in network.yaml and store it in an array
+          
+            #Get information about each node from network.yaml and store it in an array
             declare -a node
             declare -a nodeOrg
             declare -a nodeType
@@ -157,10 +175,6 @@ spec:
             node+=(${NODE_NAME})
             nodeOrg+=(${NODE_ORG})
             nodeType+=(${NODE_TYPE})
-
-            echo "node names: ${node[@]}"
-            echo "node organizations: ${nodeOrg[@]}"
-            echo "node types: ${nodeType[@]}"
             
             # for data in "${org[@]}";
             # do
@@ -176,15 +190,11 @@ spec:
             #   fi
             # done
             
-            #generate crypto for IBFT consensus
-            echo "generate crypto for IBFT consensus"
-            /opt/besu/bin/besu operator generate-blockchain-config  --config-file=/genesis-raw-config/ibftConfigFile.json --to=${BUILD_PATH}/crypto  --private-key-file-name=key_private
-            # ls -l ${BUILD_PATH}/crypto
-            #get the list of files created by besu in crypto directory
-            # echo "Files created by besu: " 
-            # find ${BUILD_PATH}/crypto/keys/ -type f
-            #ls -l ${BUILD_PATH}/crypto/keys/
-
+            #Generate crypto for IBFT consensus
+            echo "Generating crypto for IBFT consensus"
+            /opt/besu/bin/besu operator generate-blockchain-config  --config-file=/genesis-raw-config/ibftConfigFile.json --to=${BUILD_PATH}/crypto  --private-key-file-name=key
+            
+            #Find folders created by besu in the above command, and rename them with node information
             declare -a FILE_PATH
             declare -a DEST
 
@@ -207,140 +217,116 @@ spec:
               echo "Destination files:"
               ls -l ${DEST[i]}/
 
-              # setting up env to login vault
+              #Save the keys to vault
+              echo "Copying keys to vault..."
+              #Setting up env to login vault
               KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
               VAULT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login -H "Content-Type: application/json" -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | jq -r 'if .errors then . else .auth.client_token end')
-              # validateVaultResponse 'vault login token' "${VAULT_TOKEN}"
+              validateVaultResponse 'vault login token' "${VAULT_TOKEN}"
               echo "Logged into Vault"
 
-              # Copy the crypto material to the Vault
-              LOOKUP_SECRET_RESPONSE=$(curl -sS -H "X-Vault-Token: ${VAULT_TOKEN}" \
-               -H "Content-Type: application/json" \
-               -X POST \
-               -d '{"key_private":"'"$(cat ${DEST[i]}/key_private)"'"}' ${VAULT_ADDR}/v1/${VAULT_SECRET_PREFIX}/${node[i]}/data | jq -r 'if .errors then . else .auth.client_token end')
-            done
-            echo "copied key_private to the vault"
-
-            #create file to store addresses of validator nodes
-            touch ${BUILD_PATH}/validatorinfo
-            #ls -l ${BUILD_PATH}/
-
-            for i in "${!node[@]}";
-            do
-              data_path=${BUILD_PATH}/crypto/${nodeOrg[i]}/${node[i]}/data
-              export_address=${BUILD_PATH}/crypto/${nodeOrg[i]}/${node[i]}/data/nodeAddress
-              
-              #generate the node address for each node
-              /opt/besu/bin/besu --data-path ${data_path} public-key export-address --to=${export_address}
-
-              echo "nodeAddress file check: "
-              cat ${export_address}
-              
-              base64 ${export_address} > nodeAddress_base64
-
-              #copy the node addresses to the vault
-              #setting up env to login vault
-              KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
-              VAULT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login -H "Content-Type: application/json" -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | jq -r 'if .errors then . else .auth.client_token end')
-              # validateVaultResponse 'vault login token' "${VAULT_TOKEN}"
-              echo "Logged into Vault"
-
-              # Copy the crypto material to the Vault
+              #Copy the crypto material to Vault
               LOOKUP_SECRET_RESPONSE=$(curl -sS -H "X-Vault-Token: ${VAULT_TOKEN}" \
                 -H "Content-Type: application/json" \
                 -X POST \
-                -d '{"nodeAddress_base64":"'"$(cat ${BUILD_PATH}/crypto/${nodeOrg[i]}/${node[i]}/data/nodeAddress)"'"}' ${VAULT_ADDR}/v1/${VAULT_SECRET_PREFIX}/${node[i]}/data | jq -r 'if .errors then . else .auth.client_token end')
-               echo "copied node addresses to the vault"
+                -d '{"key":"'"$(cat ${DEST[i]}/key)"'"}' ${VAULT_ADDR}/v1/${VAULT_SECRET_PREFIX}/${node[i]}/data | jq -r 'if .errors then . else .auth.client_token end')
+
+              #Copy the crypto material to Vault
+              LOOKUP_SECRET_RESPONSE=$(curl -sS -H "X-Vault-Token: ${VAULT_TOKEN}" \
+                -H "Content-Type: application/json" \
+                -X POST \
+                -d '{"key_pub":"'"$(cat ${DEST[i]}/key.pub)"'"}' ${VAULT_ADDR}/v1/${VAULT_SECRET_PREFIX}/${node[i]}/data | jq -r 'if .errors then . else .auth.client_token end')
+            done
+            echo "Saved the keys in vault"
+
+            #create file to store addresses of validator nodes
+            touch ${BUILD_PATH}/validatorinfo
+            
+            #Generate node address for each node
+            for i in "${!node[@]}";
+            do
+              data_path=${BUILD_PATH}/crypto/${nodeOrg[i]}/${node[i]}/data
+              export_address=${data_path}/nodeAddress
+              echo "Generating node address..."
+              /opt/besu/bin/besu --data-path ${data_path} public-key export-address --to=${export_address}
+
+              echo "Check key files for ${node[i]}"
+              ls -l /opt/besu/build/crypto/${nodeOrg[i]}/${node[i]}/data/
+
+              echo "Check nodeAddress content for ${node[i]}:"
+              cat ${export_address}
+              
+              base64 ${export_address} > nodeAddress_base64
+              echo "base 64 encoded node address for ${node[i]}:"
+              cat nodeAddress_base64
+
+              #Save the node addresses in vault
+              echo "Copying node addresses to vault..."
+              #Setting up env to login vault
+              KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
+              VAULT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login -H "Content-Type: application/json" -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | jq -r 'if .errors then . else .auth.client_token end')
+              validateVaultResponse 'vault login token' "${VAULT_TOKEN}"
+              echo "Logged into Vault"
+
+              #Copy the crypto material to Vault
+              LOOKUP_SECRET_RESPONSE=$(curl -sS -H "X-Vault-Token: ${VAULT_TOKEN}" \
+                -H "Content-Type: application/json" \
+                -X POST \
+                -d '{"nodeAddress_base64":"'"$(cat ${export_address})"'"}' ${VAULT_ADDR}/v1/${VAULT_SECRET_PREFIX}/${nodeOrg[i]}/${node[i]}/data | jq -r 'if .errors then . else .auth.client_token end')
+               echo "Copied the node addresses to vault"
+
               # if [${ADD_NEW_ORG} == "True"]; then
               #   #generate the node public key for each peer of new organization
               #   export_key_path=${BUILD_PATH}/crypto/${nodeOrg[i]}/${node[i]}/data/key.pub
               #   /opt/besu/bin/besu --data-path ${data_path} public-key export --to=${export_key_path}
               # fi
 
-              # #create the validator address array
+              #Create the validator address array
               if [[ ${nodeType[i]} == "validator" ]]; then
                 echo "\"$(cat ${export_address})\"" >> ${BUILD_PATH}/validatorinfo
               fi
-              
             done
             
+            echo "Checking validator info array for ${nodeType[i]}:"
             cat ${BUILD_PATH}/validatorinfo
 
-            #this file is used by besu binary to generate the extra data information
+            #toEncode.json file is used by besu binary to generate the extra data information
             touch ${BUILD_PATH}/toEncode.json
             touch ${BUILD_PATH}/extraData
             ls -l ${BUILD_PATH}/
 
-            #new genesis file with extradata information
+            #New genesis file with extradata information
             touch ${BUILD_PATH}/crypto/newGenesis.json
             ls -l ${BUILD_PATH}/crypto
 
             #create the rlp encoded string and add it to extraData field in newGenesis.json
             cat ${BUILD_PATH}/validatorinfo | paste -sd "," -| awk '{print "["$0"]"}'> ${BUILD_PATH}/toEncode.json
-            echo "$(/opt/besu/bin/besu rlp encode --from=${BUILD_PATH}/toEncode.json )" > ${BUILD_PATH}/extraData
+            echo "$(/opt/besu/bin/besu rlp encode --from=${BUILD_PATH}/toEncode.json)" > ${BUILD_PATH}/extraData
             jq '.extraData = $newVal' --arg newVal $(cat ${BUILD_PATH}/extraData) << cat ${BUILD_PATH}/crypto/genesis.json > ${BUILD_PATH}/crypto/newGenesis.json
 
             base64 ${BUILD_PATH}/crypto/newGenesis.json > genesis_base64
+
+            echo "check genesis base64:"
+            cat genesis_base64
 
             # #delete the keys directory
             # rm -r ${BUILD_PATH}/crypto/keys
             # ls -l  ${BUILD_PATH}/crypto/keys
         
-            #copy crypto to vault
-            echo "Copy the crypto material to the vault"
+            #Save the modified genesis file with extra data info to vault
+            echo "Copying the genesis_base64 to vault..."
 
-            validateVaultResponse () {
-                if echo ${2} | grep "errors"; then
-                  echo "ERROR: unable to retrieve ${1}: ${2}"
-                  exit 1
-                fi
-                if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-                then
-                  http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-                  --header "X-Vault-Token: ${VAULT_TOKEN}" \
-                  ${VAULT_ADDR}/v1/${1})
-                  curl_response=$?
-                  if test "$http_code" != "200" ; then
-                    echo "Http response code from Vault - $http_code and curl_response - $curl_response"
-                    if test "$curl_response" != "0"; then
-                      echo "Error: curl command failed with error code - $curl_response"
-                      exit 1
-                    fi
-                  fi
-                fi
-              }
-            
-            # GENESIS_VAULT_PATH="${BUILD_PATH}/crypto/newGenesis.json"
-
-            # setting up env to login vault
+            #Setting up env to login vault
             KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
             VAULT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login -H "Content-Type: application/json" -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | jq -r 'if .errors then . else .auth.client_token end')
             validateVaultResponse 'vault login token' "${VAULT_TOKEN}"
-              echo "Logged into Vault"
+            echo "Logged into Vault"
 
-            # # Copy the crypto material to the Vault
-            # LOOKUP_SECRET_RESPONSE=$(curl -sS -H "X-Vault-Token: ${VAULT_TOKEN}" \
-            #  -H "Content-Type: application/json" \
-            #  -X POST \
-            #  -d '{"key":"'"$(cat${BUILD_PATH}/crypto/${COMPONENT_NAME}/${PEER_NAME}/data/key)"'"}' ${VAULT_ADDR}/v1/${VAULT_SECRET_PREFIX}/${PEER_NAME}/data | jq -r 'if .errors then . else .auth.client_token end')
-          
-            # Copy the crypto material to the Vault
+            #Copy genesis to vault
             LOOKUP_SECRET_RESPONSE=$(curl -sS -H "X-Vault-Token: ${VAULT_TOKEN}" \
-             -H "Content-Type: application/json" \
-             -X POST \
-             -d '{"key_pub":"'"$(cat${BUILD_PATH}/crypto/${COMPONENT_NAME}/${PEER_NAME}/data/key.pub)"'"}' ${VAULT_ADDR}/v1/${VAULT_SECRET_PREFIX}/${PEER_NAME}/data | jq -r 'if .errors then . else .auth.client_token end')
-
-            # # Copy the crypto material to the Vault
-            # LOOKUP_SECRET_RESPONSE=$(curl -sS -H "X-Vault-Token: ${VAULT_TOKEN}" \
-            #  -H "Content-Type: application/json" \
-            #  -X POST \
-            #  -d '{"nodeAddress":"'"$(cat${BUILD_PATH}/crypto/${COMPONENT_NAME}/${PEER_NAME}/data/nodeAddress)"'"}' ${VAULT_ADDR}/v1/${VAULT_SECRET_PREFIX}/${PEER_NAME}/data | jq -r 'if .errors then . else .auth.client_token end')
-
-            # Copy genesis to vault
-            LOOKUP_SECRET_RESPONSE=$(curl -sS -H "X-Vault-Token: ${VAULT_TOKEN}" \
-             -H "Content-Type: application/json" \
-             -X POST \
-             -d '{"genesis":"'"$(cat genesis_base64)"'"}' ${VAULT_ADDR}/v1/${VAULT_SECRET_PREFIX}/genesis | jq -r 'if .errors then . else .auth.client_token end')
-             echo "Done copying crypto material to the vault"
+              -H "Content-Type: application/json" \
+              -X POST \
+              -d '{"genesis":"'"$(cat ${BUILD_PATH}/crypto/genesis_base64)"'"}' ${VAULT_ADDR}/v1/${VAULT_SECRET_PREFIX}/genesis | jq -r 'if .errors then . else .auth.client_token end')
+              echo "Done copying genesis to the vault"
         
        
