[ci skip] Pushing deployment files for besu expressapi
Signed-off-by: kaverikhaneja <kaveri.khaneja@accenture.com>

diff --git a/examples/supplychain-app/charts/express_api_besu/templates/deployment.yaml b/examples/supplychain-app/charts/express_api_besu/templates/deployment.yaml
--- a/examples/supplychain-app/charts/express_api_besu/templates/deployment.yaml
+++ b/examples/supplychain-app/charts/express_api_besu/templates/deployment.yaml
@@ -65,41 +65,62 @@ spec:
           - |-
             #!/usr/bin/env sh
             validateVaultResponse () {
-            if echo ${2} | grep "errors"; then
-              echo "ERROR: unable to retrieve ${1}: ${2}"
-              exit 1
-              fi
-            }
-            KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
-            echo "Getting secrets from Vault Server: ${VAULT_ADDR}"
-            #Login to Vault and so I can get an approle token
-            VAULT_CLIENT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login \
-              -H "Content-Type: application/json" \
-              -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | \
-              jq -r 'if .errors then . else .auth.client_token end')
-            validateVaultResponse 'vault login token' "${VAULT_CLIENT_TOKEN}"
-  
-            vault_secret_key="${VAULT_SECRET_PREFIX}/{{ .Values.vault.contractName }}"
-            echo "Getting the contract address from $vault_secret_key"          
-            LOOKUP_SECRET_RESPONSE=$(curl -sS \
-              --header "X-Vault-Token:${VAULT_CLIENT_TOKEN}" \
-              ${VAULT_ADDR}/v1/${vault_secret_key} | \
-              jq -r 'if .errors then . else . end')
-            validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" 
-            product_contract_address=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["address"]')
+                if echo ${2} | grep "errors"; then
+                  echo "ERROR: unable to retrieve ${1}: ${2}"
+                  exit 1
+                fi
+                if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
+                then
+                  http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
+                  --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
+                  ${VAULT_ADDR}/v1/${vault_secret_key})
+                  curl_response=$?
+                  if test "$http_code" != "200" ; then
+                      echo "Http response code from Vault - $http_code"
+                      if test "$curl_response" != "0"; then
+                        echo "Error: curl command failed with error code - $curl_response"
+                        exit 1
+                      fi
+                  fi
+                fi
+              }
+              KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
+              echo "Getting secrets from Vault Server: ${VAULT_ADDR}"
 
-            LOOKUP_SECRET_RESPONSE=$(curl -X POST \
-              --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":"*"}' -H "Content-Type: application/json" \
-              {{ .Values.expressapp.env.geth_address }} | \
-              jq -r 'if .errors then . else . end')
-            validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" 
-            node_identity=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.result[0]')
+              #Login to Vault and so I can get an approle token
+              VAULT_CLIENT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login \
+                -H "Content-Type: application/json" \
+                -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | \
+                jq -r 'if .errors then . else .auth.client_token end')
+              validateVaultResponse 'vault login token' "${VAULT_CLIENT_TOKEN}"
+              echo "Logged into Vault"
   
-            OUTPUT_PATH="${MOUNT_PATH}/keys"
-            mkdir -p ${OUTPUT_PATH}
+              vault_secret_key="${VAULT_SECRET_PREFIX}/{{ .Values.vault.contractName }}"
 
-            echo -n "${product_contract_address}" > ${OUTPUT_PATH}/product_contract_address
-            echo -n "${node_identity}" > ${OUTPUT_PATH}/node_identity
+              echo "Getting the contract address from $vault_secret_key"          
+              LOOKUP_SECRET_RESPONSE=$(curl -sS \
+                --header "X-Vault-Token:${VAULT_CLIENT_TOKEN}" \
+                ${VAULT_ADDR}/v1/${vault_secret_key} | \
+                jq -r 'if .errors then . else . end')
+              validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+              product_contract_address=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["address"]')
+
+              echo "Contract address: ${product_contract_address}"
+
+              LOOKUP_SECRET_RESPONSE=$(curl -X POST \
+                --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":"*"}' -H "Content-Type: application/json" \
+                {{ .Values.expressapp.env.geth_address }} | \
+                jq -r 'if .errors then . else . end')
+              validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+              node_identity=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.result[0]')
+
+              echo "Node identity: ${node_identity}"
+  
+              OUTPUT_PATH="${MOUNT_PATH}/keys"
+              mkdir -p ${OUTPUT_PATH}
+
+              echo -n "${product_contract_address}" > ${OUTPUT_PATH}/product_contract_address
+              echo -n "${node_identity}" > ${OUTPUT_PATH}/node_identity
       containers:     
         - name: express-app
           image: {{ .Values.expressapp.image }}
